### PR TITLE
Get `SymPair` to return `Option<Symbol>`

### LINKED ISSUE #195: Does unbound_value need to be exposed just to support pairlist creation from string tuples?
(second round of #187)

### Background

When we call a function, there's two types of cases:

1. use a fixed number of arguments that is determined on compile
2. use an arbitrary number of arguments that is determined on runtime

For case 1, we'll able to write as the following after #190.

``` r
f.call(pairlist!(a = r!(1), r(2)))
```

We can provide more sophisticated interface by using procedural macro. However, case 2 is a different problem. As the structure of the argument is determined on runtime, the macro cannot solve the problem, iiuc. If you are curious about the real use case, please refer to my experimental package: https://github.com/yutannihilation/rr4r#rr4r_replace

The problem is how to handle named and unnamed arguments transparently. The implementation in #190 solves this by treating `""` and `na_str()` as `R_UnboundValue` so that we can write:

``` rust
let pairs = vec![("a", r!(1)), (na_str(), r!(2))];
let pairlist = Pairlist::from_pairs(pairs);
f.call(pairlist.into_robj()).unwrap()
```

### Problem

While the current approach works, I'm afraid it makes the handling of symbols different from what it should be; It differs from the behaviour of usual R functions,

``` r
as.name("")
#> Error in as.name(""): attempt to use zero-length variable name
as.name(NA_character_)
#> `NA`
```

<sup>Created on 2021-03-19 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

and exposing `unbound_value()` to users might be a bit too low-level.

```
> rextendr::rust_function(r"(
+ fn as_sym(x: String) -> Robj {
+   Symbol::from_str(x.as_str()).into_robj()
+ }
+ )", patch.crates_io = list(`extendr-api` = list(git = "https://github.com/extendr/extendr", branch = "more-wrapper-tidying"))
+ )
build directory: /tmp/RtmpafHjhM/file13fe8440d442b

    Updating crates.io index
   Compiling rextendr9 v0.0.1 (/tmp/RtmpafHjhM/file13fe8440d442b)
    Finished dev [unoptimized + debuginfo] target(s) in 1.69s
✓ Writing wrappers to /tmp/RtmpafHjhM/file13fe8440d442b/target/extendr_wrappers.R.
> x <- as_sym("")
Error: attempt to bind a variable to R_UnboundValue
> as_sym("")
Error: invalid multibyte string at '<90><c0><a8>y<f4>U'
```

Can we let the construction of a pairlist just work without tweaking the symbols' interface?

### How do cpp11/Rcpp handle pairlists?

For case 1, cpp11 uses variadic template and polymorphism to treat named and unnamed argument differently. I guess the same thing can be done by procedural macro. 

* operator `()`: https://github.com/r-lib/cpp11/blob/3c65bc56250a882613ed919d271b789aad557402/inst/include/cpp11/function.hpp#L20-L54
* `named_arg`: https://github.com/r-lib/cpp11/blob/c41056b557cabd30bb2e5b901ca92a26262e7718/inst/include/cpp11/named_arg.hpp#L11-L38

For case 2, I couldn't find the interface (maybe due to my lack of C++ skill). Maybe users need to create an unnamed list and then `set_names()`? This also looks fine to me.

### PR DESCRIPTION
**Pull request by yutannihilation**
Fix #195 

This pull request is to remove the necessity to use unbound value to represent the absence of the name. I decided to follow [Andy's comment](https://github.com/extendr/extendr/issues/195#issuecomment-817832510). Instead, users can use `""` (empty string).

This is consistent with the behavior of R (c.f. https://github.com/extendr/extendr/issues/195#issuecomment-803497556, https://github.com/extendr/extendr/issues/195#issuecomment-803498672)

While this is a breaking change in that `SymPair::sym_pair()` now returns `(Option<Robj>, Robj)` instead of `(Robj, Robj)`, I expect this doesn't affect the existing users much as this is rather an expert-only feature at the moment.

### CODE REVIEW

File: extendr-api/src/wrapper/environment.rs [hunk 1]
```diff
@@ -65,7 +65,9 @@ impl Environment {
             let robj = call!("new.env", TRUE, parent, dict_len).unwrap();
             for nv in names_and_values {
                 let (n, v) = nv.sym_pair();
-                unsafe { Rf_defineVar(n.get(), v.get(), robj.get()) }
+                if let Some(n) = n {
+                    unsafe { Rf_defineVar(n.get(), v.get(), robj.get()) }
+                }
```
Comment (yutannihilation) [inline extendr-api/src/wrapper/environment.rs:70]: One thing not very obvious is what we should do when the user try to create an environment from a pairlist containing unnamed element. Currently it's just ignored. Should we raise an error?

Comment (clauswilke) [reply extendr-api/src/wrapper/environment.rs:70]: What is ignored? The unnamed element only, or the entire call? And if you triggered an error, would it be compile time or runtime?

File: extendr-api/src/wrapper/symbol.rs [hunk 2]
```diff
@@ -18,25 +18,17 @@ pub struct Symbol {
...
     /// ```
     pub fn from_string<S: AsRef<str>>(val: S) -> Self {
         let val = val.as_ref();
-        if val.is_empty() || val.is_na() {
-            unbound_value()
-        } else {
-            Symbol {
-                robj: unsafe { new_owned(make_symbol(val)) },
-            }
+        Symbol {
```
Comment (clauswilke) [inline extendr-api/src/wrapper/symbol.rs:30]: Just so I understand: What happens now if `val` is empty or is `NA`? Why don't we need to check for this anymore?

**Comment by clauswilke** [comment]
I have reviewed this but don't feel qualified to assess whether the change from `(Robj, Robj)` to `(Option<Robj>, Robj)` will cause any issues. @andy-thomason Could you review also?

File: extendr-api/src/wrapper/environment.rs (hunk 1 above)
Comment (yutannihilation) [reply extendr-api/src/wrapper/environment.rs:70]: > The unnamed element only, or the entire call?

Currently this ignores the unnamed elements only.

> And if you triggered an error, would it be compile time or runtime?

Runtime.

File: extendr-api/src/wrapper/symbol.rs (hunk 2 above)
Comment (yutannihilation) [reply extendr-api/src/wrapper/symbol.rs:30]: They are just passed to R's C API. So, these two should behave in the same way as how R does.

```
as.name("")
#> Error in as.name(""): attempt to use zero-length variable name
as.name(NA_character_)
#> `NA`
```

File: extendr-api/src/wrapper/environment.rs (hunk 1 above)
Comment (clauswilke) [reply extendr-api/src/wrapper/environment.rs:70]: It's unclear to me. Usually, my philosophy is that code should use meaningful fallback behavior on empty input, so that would argue against raising an error. I have encountered so many cases where code would complain about `NA` or `NULL` input instead of silently ignoring it, and then I have to special-case these situations, and the code I'm calling is also special-casing, and it just doesn't make sense.

I assume the counter-argument is that silently ignoring invalid input can create difficult-to-find bugs.

Comment (yutannihilation) [reply extendr-api/src/wrapper/environment.rs:70]: I'm getting inclined to raise an error, rather than handling the invalid inputs gracefully. I think this operation is for special cases when there's a lot of inputs generated programmatically, as the example shows. For more dynamic inputs, users can process the elements one by one with `Environment::set_local()` by themselves.

``` rust
    ///     let names_and_values = (0..100).map(|i| (format!("n{}", i), i));
    ///     let mut env = Environment::from_pairs(global_env(), names_and_values);
    ///     assert_eq!(env.len(), 100);
```

Comment (clauswilke) [reply extendr-api/src/wrapper/environment.rs:70]: Ok, sounds good to me.

**Review by andy-thomason — APPROVED** [review]
It should be a bit faster if anything.

It is also a bit clearer when names are not present.
